### ISSUE TITLE
choices won't return correctly

### ISSUE THREAD

**Issue by Eisenbahn** [EnvyWare/Pixelmon-Skript-Extension#1]
![image](https://github.com/EnvyWare/Pixelmon-Skript-Extension/assets/2753064/4b7c7d39-b623-4067-927b-6b7352b9703f)

I'm using your examples:

```
command /dbdia:
	trigger:
		add "Test one" to {_choices::*}
		add "Test two" to {_choices::*}
		dialogue for player title "Hello World" description "Description!" with {_choices::*}


on choice:
  set {_player} to player
  set {_choice} to choice
  message "%{_player}% %{_choice}%"
```

**Comment by danorris709** [comment]
You need to do event-choice

**Comment by Eisenbahn** [comment]
Yeah, worked. But I did used your own example:

![image](https://github.com/EnvyWare/Pixelmon-Skript-Extension/assets/2753064/e3d52a12-28c4-4a87-879b-bf65ff7f06df)

Thank you!
Peace!

**Comment by danorris709** [comment]
Ah I forgot to update the Spigot page, apologies!
